"""Canonical Kafka topic names for the smart-ecommerce platform."""

CART_CHECKOUT = "cart.checkout"
ORDER_CREATED = "order.created"
ORDER_AWAITING_PAYMENT = "order.awaiting_payment"
ORDER_CONFIRMED = "order.confirmed"
ORDER_CANCELLED = "order.cancelled"
INVENTORY_RESERVED = "inventory.reserved"
INVENTORY_RESERVATION_FAILED = "inventory.reservation_failed"
INVENTORY_RESERVATION_CANCEL = "inventory.reservation_cancel"
FRAUD_FLAGGED = "fraud.flagged"
PAYMENT_SUCCEEDED = "payment.succeeded"
PAYMENT_FAILED = "payment.failed"
PRODUCT_VIEWED = "product.viewed"
