topics:
  - name: order.created
    partitions: 3
    replicationFactor: 1
  - name: inventory.reserved
    partitions: 3
    replicationFactor: 1
  - name: inventory.reservation_failed
    partitions: 3
    replicationFactor: 1
  - name: fraud.flagged
    partitions: 3
    replicationFactor: 1
  - name: order.awaiting_payment
    partitions: 3
    replicationFactor: 1
  - name: payment.succeeded
    partitions: 3
    replicationFactor: 1
  - name: payment.failed
    partitions: 3
    replicationFactor: 1
  - name: order.confirmed
    partitions: 3
    replicationFactor: 1
  - name: order.cancelled
    partitions: 3
    replicationFactor: 1
  - name: product.viewed
    partitions: 3
    replicationFactor: 1
  - name: cart.checkout
    partitions: 3
    replicationFactor: 1
  - name: inventory.reservation_cancel
    partitions: 3
    replicationFactor: 1
